
import React, { useState, useEffect } from 'react';
import { BrainCircuit, X, Sparkles, Loader2 } from 'lucide-react';

interface NutritionAdvisorModalProps {
  isOpen: boolean;
  onClose: () => void;
  isLoading: boolean;
  advice: string;
}

const NutritionAdvisorModal: React.FC<NutritionAdvisorModalProps> = ({ 
  isOpen, 
  onClose, 
  isLoading, 
  advice 
}) => {
  const [displayedAdvice, setDisplayedAdvice] = useState('');

  useEffect(() => {
    if (isOpen && advice && !isLoading) {
      setDisplayedAdvice('');
      let currentIndex = 0;
      const textLength = advice.length;
      
      // Animate text
      const intervalId = setInterval(() => {
        if (currentIndex >= textLength) {
          clearInterval(intervalId);
          return;
        }
        // Add chunks of text for better performance and pacing
        const chunkValues = 3;
        currentIndex = Math.min(currentIndex + chunkValues, textLength);
        setDisplayedAdvice(advice.slice(0, currentIndex));
      }, 10);

      return () => clearInterval(intervalId);
    } else if (!isOpen) {
      setDisplayedAdvice('');
    }
  }, [isOpen, advice, isLoading]);

  if (!isOpen) return null;

  const renderFormattedText = (text: string) => {
    // Split string by bold markdown syntax **...**
    return text.split(/(\*\*.*?\*\*)/g).map((part, index) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={index} className="font-bold text-indigo-900 dark:text-indigo-300">{part.slice(2, -2)}</strong>;
      }
      return part;
    });
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-2xl w-full max-w-md overflow-hidden border border-slate-100 dark:border-slate-800 relative animate-in zoom-in-95 duration-200 transition-colors">
        
        {/* Header */}
        <div className="p-5 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between bg-indigo-50/50 dark:bg-indigo-900/20">
          <div className="flex items-center space-x-2">
            <div className="p-2 bg-indigo-100 dark:bg-indigo-900/40 rounded-lg">
              <BrainCircuit className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
            </div>
            <div>
              <h3 className="font-bold text-slate-800 dark:text-slate-100">Nutrition Advisor</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">AI-Powered Daily Analysis</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 min-h-[200px] max-h-[60vh] overflow-y-auto custom-scrollbar">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center h-full py-8 space-y-4">
              <Loader2 className="w-8 h-8 text-indigo-600 dark:text-indigo-400 animate-spin" />
              <p className="text-sm text-slate-500 dark:text-slate-400 animate-pulse">Analyzing your macros...</p>
            </div>
          ) : (
            <div className="prose prose-sm prose-indigo dark:prose-invert text-slate-600 dark:text-slate-300 leading-relaxed whitespace-pre-wrap">
              {renderFormattedText(displayedAdvice)}
              <span className="inline-block w-1.5 h-4 ml-0.5 bg-indigo-500 animate-pulse align-middle" style={{ opacity: displayedAdvice.length < advice.length ? 1 : 0 }}></span>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 bg-slate-50 dark:bg-slate-850 border-t border-slate-100 dark:border-slate-800 text-center">
          <div className="flex items-center justify-center space-x-2 text-xs text-slate-400 dark:text-slate-500">
            <Sparkles className="w-3 h-3" />
            <span>Generated by DeepSeek AI based on your current logs</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default NutritionAdvisorModal;
